export type Cancion = {
  id: number;
  titulo: string;
  banda: string;
  album: string;
};

export const canciones: Cancion[] = [
    { id: 1, titulo: 'Rock and Roll', banda: 'Led Zeppelin', album: 'Led Zeppelin IV' },
    { id: 2, titulo: 'Black Dog', banda: 'Led Zeppelin', album: 'Led Zeppelin IV' },
    { id: 3, titulo: 'The Battle of Evermore', banda: 'Led Zeppelin', album: 'Led Zeppelin IV' },
    { id: 4, titulo: 'Stairway to Heaven', banda: 'Led Zeppelin', album: 'Led Zeppelin IV' },
    { id: 5, titulo: 'Misty Mountain Hop', banda: 'Led Zeppelin', album: 'Led Zeppelin IV' },
    { id: 6, titulo: 'Four Sticks', banda: 'Led Zeppelin', album: 'Led Zeppelin IV' },
    { id: 7, titulo: 'Going to California', banda: 'Led Zeppelin', album: 'Led Zeppelin IV' },
    { id: 8, titulo: 'When the Levee Breaks', banda: 'Led Zeppelin', album: 'Led Zeppelin IV' },
    { id: 9, titulo: 'Custard Pie', banda: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 10, titulo: 'The Rover', banda: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 11, titulo: 'In My Time of Dying', banda: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 12, titulo: 'Houses of the Holy', banda: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 13, titulo: 'Trampled Under Foot', banda: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 14, titulo: 'Kashmir', banda: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 15, titulo: 'In the Light', banda: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 16, titulo: 'Bron-Yr-Aur', banda: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 17, titulo: 'Down by the Seaside', banda: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 18, titulo: 'Ten Years Gone', banda: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 19, titulo: 'Night Flight', banda: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 20, titulo: 'The Wanton Song', banda: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 21, titulo: 'Boogie with Stu', banda: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 22, titulo: 'Black Country Woman', banda: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 23, titulo: 'Sick Again', banda: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 24, titulo: 'The Song Remains the Same', banda: 'Led Zeppelin', album: 'Houses of the Holy' },
    { id: 25, titulo: 'The Rain Song', banda: 'Led Zeppelin', album: 'Houses of the Holy' },
    { id: 26, titulo: 'Over the Hills and Far Away', banda: 'Led Zeppelin', album: 'Houses of the Holy' },
    { id: 27, titulo: "The Crunge", banda: 'Led Zeppelin', album: 'Houses of the Holy' },
    { id: 28, titulo: "D'yer Mak'er", banda: 'Led Zeppelin', album: 'Houses of the Holy' },
    { id: 29, titulo: 'No Quarter', banda: 'Led Zeppelin', album: 'Houses of the Holy' },
    { id: 30, titulo: 'The Ocean', banda: 'Led Zeppelin', album: 'Houses of the Holy' },
    { id: 31, titulo: 'Whole Lotta Love', banda: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 32, titulo: 'What Is and What Should Never Be', banda: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 33, titulo: 'The Lemon Song', banda: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 34, titulo: 'Thank You', banda: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 35, titulo: 'Heartbreaker', banda: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 36, titulo: "Living Loving Maid (She's Just A Woman)", banda: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 37, titulo: 'Ramble On', banda: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 38, titulo: 'Moby Dick', banda: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 39, titulo: 'Bring It On Home', banda: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 40, titulo: 'In the Evening', banda: 'Led Zeppelin', album: 'In Through the Out Door' },
    { id: 41, titulo: 'South Bound Saurez', banda: 'Led Zeppelin', album: 'In Through the Out Door' },
    { id: 42, titulo: 'Fool in the Rain', banda: 'Led Zeppelin', album: 'In Through the Out Door' },
    { id: 43, titulo: 'Hot Dog', banda: 'Led Zeppelin', album: 'In Through the Out Door' },
    { id: 44, titulo: 'Carouselambra', banda: 'Led Zeppelin', album: 'In Through the Out Door' },
    { id: 45, titulo: 'All My Love', banda: 'Led Zeppelin', album: 'In Through the Out Door' },
    { id: 46, titulo: "I'm Gonna Crawl", banda: 'Led Zeppelin', album: 'In Through the Out Door' },
    { id: 47, titulo: 'Hells Bells', banda: 'AC/DC', album: 'Back in Black' },
    { id: 48, titulo: 'Shoot to Thrill', banda: 'AC/DC', album: 'Back in Black' },
    { id: 49, titulo: 'What Do You Do for Money Honey', banda: 'AC/DC', album: 'Back in Black' },
    { id: 50, titulo: 'Given the Dog a Bone', banda: 'AC/DC', album: 'Back in Black' },
    { id: 51, titulo: 'Let Me Put My Love into You', banda: 'AC/DC', album: 'Back in Black' },
    { id: 52, titulo: 'Back in Black', banda: 'AC/DC', album: 'Back in Black' },
    { id: 53, titulo: 'You Shook Me All Night Long', banda: 'AC/DC', album: 'Back in Black' },
    { id: 54, titulo: 'Have a Drink on Me', banda: 'AC/DC', album: 'Back in Black' },
    { id: 55, titulo: 'Shake a Leg', banda: 'AC/DC', album: 'Back in Black' },
    { id: 56, titulo: "Rock and Roll Ain't Noise Pollution", banda: 'AC/DC', album: 'Back in Black' },
    { id: 57, titulo: 'Highway to Hell', banda: 'AC/DC', album: 'Highway to Hell' },
    { id: 58, titulo: 'Girls Got Rhythm', banda: 'AC/DC', album: 'Highway to Hell' },
    { id: 59, titulo: 'Walk All Over You', banda: 'AC/DC', album: 'Highway to Hell' },
    { id: 60, titulo: 'Touch Too Much', banda: 'AC/DC', album: 'Highway to Hell' },
    { id: 61, titulo: 'Beating Around the Bush', banda: 'AC/DC', album: 'Highway to Hell' },
    { id: 62, titulo: 'Shot Down in Flames', banda: 'AC/DC', album: 'Highway to Hell' },
    { id: 63, titulo: 'Get It Hot', banda: 'AC/DC', album: 'Highway to Hell' },
    { id: 64, titulo: "If You Want Blood (You’ve Got It)", banda: 'AC/DC', album: 'Highway to Hell' },
    { id: 65, titulo: 'Love Hungry Man', banda: 'AC/DC', album: 'Highway to Hell' },
    { id: 66, titulo: 'Night Prowler', banda: 'AC/DC', album: 'Highway to Hell' },
    { id: 67, titulo: "Rock 'n' Roll Damnation", banda: 'AC/DC', album: 'Powerage' },
    { id: 68, titulo: 'Down Payment Blues', banda: 'AC/DC', album: 'Powerage' },
    { id: 69, titulo: 'Gimme a Bullet', banda: 'AC/DC', album: 'Powerage' },
    { id: 70, titulo: 'Riff Raff', banda: 'AC/DC', album: 'Powerage' },
    { id: 71, titulo: 'Sin City', banda: 'AC/DC', album: 'Powerage' },
    { id: 72, titulo: "What’s Next to the Moon", banda: 'AC/DC', album: 'Powerage' },
    { id: 73, titulo: "Gone Shootin’", banda: 'AC/DC', album: 'Powerage' },
    { id: 74, titulo: 'Up to My Neck in You', banda: 'AC/DC', album: 'Powerage' },
    { id: 75, titulo: 'Kicked in the Teeth', banda: 'AC/DC', album: 'Powerage' },
    { id: 76, titulo: 'Thunderstruck', banda: 'AC/DC', album: 'The Razors Edge' },
    { id: 77, titulo: 'Fire Your Guns', banda: 'AC/DC', album: 'The Razors Edge' },
    { id: 78, titulo: 'Moneytalks', banda: 'AC/DC', album: 'The Razors Edge' },
    { id: 79, titulo: 'The Razors Edge', banda: 'AC/DC', album: 'The Razors Edge' },
    { id: 80, titulo: 'Mistress for Christmas', banda: 'AC/DC', album: 'The Razors Edge' },
    { id: 81, titulo: 'Rock Your Heart Out', banda: 'AC/DC', album: 'The Razors Edge' },
    { id: 82, titulo: 'Are You Ready', banda: 'AC/DC', album: 'The Razors Edge' },
    { id: 83, titulo: 'Got You by the Balls', banda: 'AC/DC', album: 'The Razors Edge' },
    { id: 84, titulo: 'Shot of Love', banda: 'AC/DC', album: 'The Razors Edge' },
    { id: 85, titulo: "Let’s Make It", banda: 'AC/DC', album: 'The Razors Edge' },
    { id: 86, titulo: 'Goodbye and Good Riddance to Bad Luck', banda: 'AC/DC', album: 'The Razors Edge' },
    { id: 87, titulo: 'If You Dare', banda: 'AC/DC', album: 'The Razors Edge' },
    { id: 88, titulo: 'Dirty Deeds Done Dirt Cheap', banda: 'AC/DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 89, titulo: 'Love at First Feel', banda: 'AC/DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 90, titulo: 'Big Balls', banda: 'AC/DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 91, titulo: 'Rocker', banda: 'AC/DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 92, titulo: 'Problem Child', banda: 'AC/DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 93, titulo: "There's Gonna Be Some Rockin'", banda: 'AC/DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 94, titulo: "Ain't No Fun (Waiting Round to Be a Millionaire)", banda: 'AC/DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 95, titulo: 'Ride On', banda: 'AC/DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 96, titulo: 'Squealer', banda: 'AC/DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 97, titulo: 'Death on Two Legs', banda: 'Queen', album: 'A Night at the Opera' },
    { id: 98, titulo: 'Lazing on a Sunday Afternoon', banda: 'Queen', album: 'A Night at the Opera' },
    { id: 99, titulo: "I'm in Love with My Car", banda: 'Queen', album: 'A Night at the Opera' },
    { id: 100, titulo: "You’re My Best Friend", banda: 'Queen', album: 'A Night at the Opera' },
    { id: 101, titulo: "'39", banda: 'Queen', album: 'A Night at the Opera' },
    { id: 102, titulo: 'Sweet Lady', banda: 'Queen', album: 'A Night at the Opera' },
    { id: 103, titulo: 'Seaside Rendezvous', banda: 'Queen', album: 'A Night at the Opera' },
    { id: 104, titulo: "The Prophet’s Song", banda: 'Queen', album: 'A Night at the Opera' },
    { id: 105, titulo: 'Love of My Life', banda: 'Queen', album: 'A Night at the Opera' },
    { id: 106, titulo: 'Good Company', banda: 'Queen', album: 'A Night at the Opera' },
    { id: 107, titulo: 'Bohemian Rhapsody', banda: 'Queen', album: 'A Night at the Opera' },
    { id: 108, titulo: 'God Save the Queen', banda: 'Queen', album: 'A Night at the Opera' },
    { id: 109, titulo: 'We Will Rock You', banda: 'Queen', album: 'News of the World' },
    { id: 110, titulo: 'We Are the Champions', banda: 'Queen', album: 'News of the World' },
    { id: 111, titulo: 'Sheer Heart Attack', banda: 'Queen', album: 'News of the World' },
    { id: 112, titulo: 'All Dead, All Dead', banda: 'Queen', album: 'News of the World' },
    { id: 113, titulo: 'Spread Your Wings', banda: 'Queen', album: 'News of the World' },
    { id: 114, titulo: 'Fight from the Inside', banda: 'Queen', album: 'News of the World' },
    { id: 115, titulo: 'Get Down, Make Love', banda: 'Queen', album: 'News of the World' },
    { id: 116, titulo: 'Sleeping on the Sidewalk', banda: 'Queen', album: 'News of the World' },
    { id: 117, titulo: 'Who Needs You', banda: 'Queen', album: 'News of the World' },
    { id: 118, titulo: "It’s Late", banda: 'Queen', album: 'News of the World' },
    { id: 119, titulo: 'My Melancholy Blues', banda: 'Queen', album: 'News of the World' },
    { id: 120, titulo: 'Play the Game', banda: 'Queen', album: 'The Game' },
    { id: 121, titulo: 'Dragon Attack', banda: 'Queen', album: 'The Game' },
    { id: 122, titulo: 'Another One Bites the Dust', banda: 'Queen', album: 'The Game' },
    { id: 123, titulo: 'Need Your Loving Tonight', banda: 'Queen', album: 'The Game' },
    { id: 124, titulo: 'Crazy Little Thing Called Love', banda: 'Queen', album: 'The Game' },
    { id: 125, titulo: 'Rock It (Prime Jive)', banda: 'Queen', album: 'The Game' },
    { id: 126, titulo: "Don’t Try Suicide", banda: 'Queen', album: 'The Game' },
    { id: 127, titulo: 'Sail Away Sweet Sister', banda: 'Queen', album: 'The Game' },
    { id: 128, titulo: 'Coming Soon', banda: 'Queen', album: 'The Game' },
    { id: 129, titulo: 'Save Me', banda: 'Queen', album: 'The Game' },
    { id: 130, titulo: 'Procession', banda: 'Queen', album: 'Queen II' },
    { id: 131, titulo: 'Father to Son', banda: 'Queen', album: 'Queen II' },
    { id: 132, titulo: 'White Queen (As It Began)', banda: 'Queen', album: 'Queen II' },
    { id: 133, titulo: 'Some Day One Day', banda: 'Queen', album: 'Queen II' },
    { id: 134, titulo: 'The Loser in the End', banda: 'Queen', album: 'Queen II' },
    { id: 135, titulo: 'Ogre Battle', banda: 'Queen', album: 'Queen II' },
    { id: 136, titulo: "The Fairy Feller’s Master-Stroke", banda: 'Queen', album: 'Queen II' },
    { id: 137, titulo: 'Nevermore', banda: 'Queen', album: 'Queen II' },
    { id: 138, titulo: 'The March of the Black Queen', banda: 'Queen', album: 'Queen II' },
    { id: 139, titulo: 'Funny How Love Is', banda: 'Queen', album: 'Queen II' },
    { id: 140, titulo: 'Seven Seas of Rhye', banda: 'Queen', album: 'Queen II' },
    { id: 141, titulo: 'Fat Bottomed Girls', banda: 'Queen', album: 'Jazz' },
    { id: 142, titulo: 'Mustapha', banda: 'Queen', album: 'Jazz' },
    { id: 143, titulo: 'Jealousy', banda: 'Queen', album: 'Jazz' },
    { id: 144, titulo: 'Bicycle Race', banda: 'Queen', album: 'Jazz' },
    { id: 145, titulo: "If You Can’t Beat Them", banda: 'Queen', album: 'Jazz' },
    { id: 146, titulo: 'Let Me Entertain You', banda: 'Queen', album: 'Jazz' },
    { id: 147, titulo: 'Dead on Time', banda: 'Queen', album: 'Jazz' },
    { id: 148, titulo: 'In Only Seven Days', banda: 'Queen', album: 'Jazz' },
    { id: 149, titulo: "Dreamer’s Ball", banda: 'Queen', album: 'Jazz' },
    { id: 150, titulo: 'Fun It', banda: 'Queen', album: 'Jazz' },
    { id: 151, titulo: "Leaving Home Ain’t Easy", banda: 'Queen', album: 'Jazz' },
    { id: 152, titulo: "Don’t Stop Me Now", banda: 'Queen', album: 'Jazz' },
    { id: 153, titulo: 'More of That Jazz', banda: 'Queen', album: 'Jazz' },
    { id: 154, titulo: 'Speak to Me', banda: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 155, titulo: 'Breathe (In the Air)', banda: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 156, titulo: 'On the Run', banda: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 157, titulo: 'Time', banda: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 158, titulo: 'The Great Gig in the Sky', banda: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 159, titulo: 'Money', banda: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 160, titulo: 'Us and Them', banda: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 161, titulo: 'Any Colour You Like', banda: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 162, titulo: 'Brain Damage', banda: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 163, titulo: 'Eclipse', banda: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 164, titulo: 'Shine On You Crazy Diamond (Parts I–V)', banda: 'Pink Floyd', album: 'Wish You Were Here' },
    { id: 165, titulo: 'Welcome to the Machine', banda: 'Pink Floyd', album: 'Wish You Were Here' },
    { id: 166, titulo: 'Have a Cigar', banda: 'Pink Floyd', album: 'Wish You Were Here' },
    { id: 167, titulo: 'Wish You Were Here', banda: 'Pink Floyd', album: 'Wish You Were Here' },
    { id: 168, titulo: 'Shine On You Crazy Diamond (Parts VI–IX)', banda: 'Pink Floyd', album: 'Wish You Were Here' },
    { id: 169, titulo: 'In the Flesh?', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 170, titulo: 'The Thin Ice', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 171, titulo: 'Another Brick in the Wall, Part 1', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 172, titulo: 'The Happiest Days of Our Lives', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 173, titulo: 'Another Brick in the Wall, Part 2', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 174, titulo: 'Mother', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 175, titulo: 'Goodbye Blue Sky', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 176, titulo: 'Empty Spaces', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 177, titulo: 'Young Lust', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 178, titulo: 'One of My Turns', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 179, titulo: "Don't Leave Me Now", banda: 'Pink Floyd', album: 'The Wall' },
    { id: 180, titulo: 'Another Brick in the Wall, Part 3', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 181, titulo: 'Goodbye Cruel World', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 182, titulo: 'Pigs on the Wing (Part 1)', banda: 'Pink Floyd', album: 'Animals' },
    { id: 183, titulo: 'Dogs', banda: 'Pink Floyd', album: 'Animals' },
    { id: 184, titulo: 'Pigs (Three Different Ones)', banda: 'Pink Floyd', album: 'Animals' },
    { id: 185, titulo: 'Sheep', banda: 'Pink Floyd', album: 'Animals' },
    { id: 186, titulo: 'Pigs on the Wing (Part 2)', banda: 'Pink Floyd', album: 'Animals' },
    { id: 187, titulo: 'Hey You', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 188, titulo: 'Is There Anybody Out There?', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 189, titulo: 'Nobody Home', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 190, titulo: 'Vera', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 191, titulo: 'Bring the Boys Back Home', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 192, titulo: 'Comfortably Numb', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 193, titulo: 'The Show Must Go On', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 194, titulo: 'In the Flesh', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 195, titulo: 'Run Like Hell', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 196, titulo: 'Waiting for the Worms', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 197, titulo: 'Stop', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 198, titulo: 'The Trial', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 199, titulo: 'Outside the Wall', banda: 'Pink Floyd', album: 'The Wall' },
    { id: 200, titulo: 'One of These Days', banda: 'Pink Floyd', album: 'Meddle' },
    { id: 201, titulo: 'A Pillow of Winds', banda: 'Pink Floyd', album: 'Meddle' },
    { id: 202, titulo: 'Fearless', banda: 'Pink Floyd', album: 'Meddle' },
    { id: 203, titulo: 'San Tropez', banda: 'Pink Floyd', album: 'Meddle' },
    { id: 204, titulo: 'Seamus', banda: 'Pink Floyd', album: 'Meddle' },
    { id: 205, titulo: 'Echoes', banda: 'Pink Floyd', album: 'Meddle' },
];
