export type Cancion = {
  id: number;
  title: string;
  artist: string;
  album: string;
};

export const canciones: Cancion[] = [
    { id: 1, title: 'Rock and Roll', artist: 'Led Zeppelin', album: 'Led Zeppelin IV' },
    { id: 2, title: 'Black Dog', artist: 'Led Zeppelin', album: 'Led Zeppelin IV' },
    { id: 3, title: 'The Battle of Evermore', artist: 'Led Zeppelin', album: 'Led Zeppelin IV' },
    { id: 4, title: 'Stairway to Heaven', artist: 'Led Zeppelin', album: 'Led Zeppelin IV' },
    { id: 5, title: 'Misty Mountain Hop', artist: 'Led Zeppelin', album: 'Led Zeppelin IV' },
    { id: 6, title: 'Four Sticks', artist: 'Led Zeppelin', album: 'Led Zeppelin IV' },
    { id: 7, title: 'Going to California', artist: 'Led Zeppelin', album: 'Led Zeppelin IV' },
    { id: 8, title: 'When the Levee Breaks', artist: 'Led Zeppelin', album: 'Led Zeppelin IV' },
    { id: 9, title: 'Custard Pie', artist: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 10, title: 'The Rover', artist: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 11, title: 'In My Time of Dying', artist: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 12, title: 'Houses of the Holy', artist: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 13, title: 'Trampled Under Foot', artist: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 14, title: 'Kashmir', artist: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 15, title: 'In the Light', artist: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 16, title: 'Bron-Yr-Aur', artist: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 17, title: 'Down by the Seaside', artist: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 18, title: 'Ten Years Gone', artist: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 19, title: 'Night Flight', artist: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 20, title: 'The Wanton Song', artist: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 21, title: 'Boogie with Stu', artist: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 22, title: 'Black Country Woman', artist: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 23, title: 'Sick Again', artist: 'Led Zeppelin', album: 'Physical Graffiti' },
    { id: 24, title: 'The Song Remains the Same', artist: 'Led Zeppelin', album: 'Houses of the Holy' },
    { id: 25, title: 'The Rain Song', artist: 'Led Zeppelin', album: 'Houses of the Holy' },
    { id: 26, title: 'Over the Hills and Far Away', artist: 'Led Zeppelin', album: 'Houses of the Holy' },
    { id: 27, title: "The Crunge", artist: 'Led Zeppelin', album: 'Houses of the Holy' },
    { id: 28, title: "D'yer Mak'er", artist: 'Led Zeppelin', album: 'Houses of the Holy' },
    { id: 29, title: 'No Quarter', artist: 'Led Zeppelin', album: 'Houses of the Holy' },
    { id: 30, title: 'The Ocean', artist: 'Led Zeppelin', album: 'Houses of the Holy' },
    { id: 31, title: 'Whole Lotta Love', artist: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 32, title: 'What Is and What Should Never Be', artist: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 33, title: 'The Lemon Song', artist: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 34, title: 'Thank You', artist: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 35, title: 'Heartbreaker', artist: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 36, title: "Living Loving Maid (She's Just A Woman)", artist: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 37, title: 'Ramble On', artist: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 38, title: 'Moby Dick', artist: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 39, title: 'Bring It On Home', artist: 'Led Zeppelin', album: 'Led Zeppelin II' },
    { id: 40, title: 'In the Evening', artist: 'Led Zeppelin', album: 'In Through the Out Door' },
    { id: 41, title: 'South Bound Saurez', artist: 'Led Zeppelin', album: 'In Through the Out Door' },
    { id: 42, title: 'Fool in the Rain', artist: 'Led Zeppelin', album: 'In Through the Out Door' },
    { id: 43, title: 'Hot Dog', artist: 'Led Zeppelin', album: 'In Through the Out Door' },
    { id: 44, title: 'Carouselambra', artist: 'Led Zeppelin', album: 'In Through the Out Door' },
    { id: 45, title: 'All My Love', artist: 'Led Zeppelin', album: 'In Through the Out Door' },
    { id: 46, title: "I'm Gonna Crawl", artist: 'Led Zeppelin', album: 'In Through the Out Door' },
    { id: 47, title: 'Hells Bells', artist: 'AC DC', album: 'Back in Black' },
    { id: 48, title: 'Shoot to Thrill', artist: 'AC DC', album: 'Back in Black' },
    { id: 49, title: 'What Do You Do for Money Honey', artist: 'AC DC', album: 'Back in Black' },
    { id: 50, title: 'Given the Dog a Bone', artist: 'AC DC', album: 'Back in Black' },
    { id: 51, title: 'Let Me Put My Love into You', artist: 'AC DC', album: 'Back in Black' },
    { id: 52, title: 'Back in Black', artist: 'AC DC', album: 'Back in Black' },
    { id: 53, title: 'You Shook Me All Night Long', artist: 'AC DC', album: 'Back in Black' },
    { id: 54, title: 'Have a Drink on Me', artist: 'AC DC', album: 'Back in Black' },
    { id: 55, title: 'Shake a Leg', artist: 'AC DC', album: 'Back in Black' },
    { id: 56, title: "Rock and Roll Ain't Noise Pollution", artist: 'AC DC', album: 'Back in Black' },
    { id: 57, title: 'Highway to Hell', artist: 'AC DC', album: 'Highway to Hell' },
    { id: 58, title: 'Girls Got Rhythm', artist: 'AC DC', album: 'Highway to Hell' },
    { id: 59, title: 'Walk All Over You', artist: 'AC DC', album: 'Highway to Hell' },
    { id: 60, title: 'Touch Too Much', artist: 'AC DC', album: 'Highway to Hell' },
    { id: 61, title: 'Beating Around the Bush', artist: 'AC DC', album: 'Highway to Hell' },
    { id: 62, title: 'Shot Down in Flames', artist: 'AC DC', album: 'Highway to Hell' },
    { id: 63, title: 'Get It Hot', artist: 'AC DC', album: 'Highway to Hell' },
    { id: 64, title: "If You Want Blood (You’ve Got It)", artist: 'AC DC', album: 'Highway to Hell' },
    { id: 65, title: 'Love Hungry Man', artist: 'AC DC', album: 'Highway to Hell' },
    { id: 66, title: 'Night Prowler', artist: 'AC DC', album: 'Highway to Hell' },
    { id: 67, title: "Rock 'n' Roll Damnation", artist: 'AC DC', album: 'Powerage' },
    { id: 68, title: 'Down Payment Blues', artist: 'AC DC', album: 'Powerage' },
    { id: 69, title: 'Gimme a Bullet', artist: 'AC DC', album: 'Powerage' },
    { id: 70, title: 'Riff Raff', artist: 'AC DC', album: 'Powerage' },
    { id: 71, title: 'Sin City', artist: 'AC DC', album: 'Powerage' },
    { id: 72, title: "What’s Next to the Moon", artist: 'AC DC', album: 'Powerage' },
    { id: 73, title: "Gone Shootin’", artist: 'AC DC', album: 'Powerage' },
    { id: 74, title: 'Up to My Neck in You', artist: 'AC DC', album: 'Powerage' },
    { id: 75, title: 'Kicked in the Teeth', artist: 'AC DC', album: 'Powerage' },
    { id: 76, title: 'Thunderstruck', artist: 'AC DC', album: 'The Razors Edge' },
    { id: 77, title: 'Fire Your Guns', artist: 'AC DC', album: 'The Razors Edge' },
    { id: 78, title: 'Moneytalks', artist: 'AC DC', album: 'The Razors Edge' },
    { id: 79, title: 'The Razors Edge', artist: 'AC DC', album: 'The Razors Edge' },
    { id: 80, title: 'Mistress for Christmas', artist: 'AC DC', album: 'The Razors Edge' },
    { id: 81, title: 'Rock Your Heart Out', artist: 'AC DC', album: 'The Razors Edge' },
    { id: 82, title: 'Are You Ready', artist: 'AC DC', album: 'The Razors Edge' },
    { id: 83, title: 'Got You by the Balls', artist: 'AC DC', album: 'The Razors Edge' },
    { id: 84, title: 'Shot of Love', artist: 'AC DC', album: 'The Razors Edge' },
    { id: 85, title: "Let’s Make It", artist: 'AC DC', album: 'The Razors Edge' },
    { id: 86, title: 'Goodbye and Good Riddance to Bad Luck', artist: 'AC DC', album: 'The Razors Edge' },
    { id: 87, title: 'If You Dare', artist: 'AC DC', album: 'The Razors Edge' },
    { id: 88, title: 'Dirty Deeds Done Dirt Cheap', artist: 'AC DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 89, title: 'Love at First Feel', artist: 'AC DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 90, title: 'Big Balls', artist: 'AC DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 91, title: 'Rocker', artist: 'AC DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 92, title: 'Problem Child', artist: 'AC DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 93, title: "There's Gonna Be Some Rockin'", artist: 'AC DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 94, title: "Ain't No Fun (Waiting Round to Be a Millionaire)", artist: 'AC DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 95, title: 'Ride On', artist: 'AC DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 96, title: 'Squealer', artist: 'AC DC', album: 'Dirty Deeds Done Dirt Cheap' },
    { id: 97, title: 'Death on Two Legs', artist: 'Queen', album: 'A Night at the Opera' },
    { id: 98, title: 'Lazing on a Sunday Afternoon', artist: 'Queen', album: 'A Night at the Opera' },
    { id: 99, title: "I'm in Love with My Car", artist: 'Queen', album: 'A Night at the Opera' },
    { id: 100, title: "You’re My Best Friend", artist: 'Queen', album: 'A Night at the Opera' },
    { id: 101, title: "'39", artist: 'Queen', album: 'A Night at the Opera' },
    { id: 102, title: 'Sweet Lady', artist: 'Queen', album: 'A Night at the Opera' },
    { id: 103, title: 'Seaside Rendezvous', artist: 'Queen', album: 'A Night at the Opera' },
    { id: 104, title: "The Prophet’s Song", artist: 'Queen', album: 'A Night at the Opera' },
    { id: 105, title: 'Love of My Life', artist: 'Queen', album: 'A Night at the Opera' },
    { id: 106, title: 'Good Company', artist: 'Queen', album: 'A Night at the Opera' },
    { id: 107, title: 'Bohemian Rhapsody', artist: 'Queen', album: 'A Night at the Opera' },
    { id: 108, title: 'God Save the Queen', artist: 'Queen', album: 'A Night at the Opera' },
    { id: 109, title: 'We Will Rock You', artist: 'Queen', album: 'News of the World' },
    { id: 110, title: 'We Are the Champions', artist: 'Queen', album: 'News of the World' },
    { id: 111, title: 'Sheer Heart Attack', artist: 'Queen', album: 'News of the World' },
    { id: 112, title: 'All Dead, All Dead', artist: 'Queen', album: 'News of the World' },
    { id: 113, title: 'Spread Your Wings', artist: 'Queen', album: 'News of the World' },
    { id: 114, title: 'Fight from the Inside', artist: 'Queen', album: 'News of the World' },
    { id: 115, title: 'Get Down, Make Love', artist: 'Queen', album: 'News of the World' },
    { id: 116, title: 'Sleeping on the Sidewalk', artist: 'Queen', album: 'News of the World' },
    { id: 117, title: 'Who Needs You', artist: 'Queen', album: 'News of the World' },
    { id: 118, title: "It’s Late", artist: 'Queen', album: 'News of the World' },
    { id: 119, title: 'My Melancholy Blues', artist: 'Queen', album: 'News of the World' },
    { id: 120, title: 'Play the Game', artist: 'Queen', album: 'The Game' },
    { id: 121, title: 'Dragon Attack', artist: 'Queen', album: 'The Game' },
    { id: 122, title: 'Another One Bites the Dust', artist: 'Queen', album: 'The Game' },
    { id: 123, title: 'Need Your Loving Tonight', artist: 'Queen', album: 'The Game' },
    { id: 124, title: 'Crazy Little Thing Called Love', artist: 'Queen', album: 'The Game' },
    { id: 125, title: 'Rock It (Prime Jive)', artist: 'Queen', album: 'The Game' },
    { id: 126, title: "Don’t Try Suicide", artist: 'Queen', album: 'The Game' },
    { id: 127, title: 'Sail Away Sweet Sister', artist: 'Queen', album: 'The Game' },
    { id: 128, title: 'Coming Soon', artist: 'Queen', album: 'The Game' },
    { id: 129, title: 'Save Me', artist: 'Queen', album: 'The Game' },
    { id: 130, title: 'Procession', artist: 'Queen', album: 'Queen II' },
    { id: 131, title: 'Father to Son', artist: 'Queen', album: 'Queen II' },
    { id: 132, title: 'White Queen (As It Began)', artist: 'Queen', album: 'Queen II' },
    { id: 133, title: 'Some Day One Day', artist: 'Queen', album: 'Queen II' },
    { id: 134, title: 'The Loser in the End', artist: 'Queen', album: 'Queen II' },
    { id: 135, title: 'Ogre Battle', artist: 'Queen', album: 'Queen II' },
    { id: 136, title: "The Fairy Feller’s Master-Stroke", artist: 'Queen', album: 'Queen II' },
    { id: 137, title: 'Nevermore', artist: 'Queen', album: 'Queen II' },
    { id: 138, title: 'The March of the Black Queen', artist: 'Queen', album: 'Queen II' },
    { id: 139, title: 'Funny How Love Is', artist: 'Queen', album: 'Queen II' },
    { id: 140, title: 'Seven Seas of Rhye', artist: 'Queen', album: 'Queen II' },
    { id: 141, title: 'Fat Bottomed Girls', artist: 'Queen', album: 'Jazz' },
    { id: 142, title: 'Mustapha', artist: 'Queen', album: 'Jazz' },
    { id: 143, title: 'Jealousy', artist: 'Queen', album: 'Jazz' },
    { id: 144, title: 'Bicycle Race', artist: 'Queen', album: 'Jazz' },
    { id: 145, title: "If You Can’t Beat Them", artist: 'Queen', album: 'Jazz' },
    { id: 146, title: 'Let Me Entertain You', artist: 'Queen', album: 'Jazz' },
    { id: 147, title: 'Dead on Time', artist: 'Queen', album: 'Jazz' },
    { id: 148, title: 'In Only Seven Days', artist: 'Queen', album: 'Jazz' },
    { id: 149, title: "Dreamer’s Ball", artist: 'Queen', album: 'Jazz' },
    { id: 150, title: 'Fun It', artist: 'Queen', album: 'Jazz' },
    { id: 151, title: "Leaving Home Ain’t Easy", artist: 'Queen', album: 'Jazz' },
    { id: 152, title: "Don’t Stop Me Now", artist: 'Queen', album: 'Jazz' },
    { id: 153, title: 'More of That Jazz', artist: 'Queen', album: 'Jazz' },
    { id: 154, title: 'Speak to Me', artist: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 155, title: 'Breathe (In the Air)', artist: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 156, title: 'On the Run', artist: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 157, title: 'Time', artist: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 158, title: 'The Great Gig in the Sky', artist: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 159, title: 'Money', artist: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 160, title: 'Us and Them', artist: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 161, title: 'Any Colour You Like', artist: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 162, title: 'Brain Damage', artist: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 163, title: 'Eclipse', artist: 'Pink Floyd', album: 'The Dark Side of the Moon' },
    { id: 164, title: 'Shine On You Crazy Diamond (Parts I–V)', artist: 'Pink Floyd', album: 'Wish You Were Here' },
    { id: 165, title: 'Welcome to the Machine', artist: 'Pink Floyd', album: 'Wish You Were Here' },
    { id: 166, title: 'Have a Cigar', artist: 'Pink Floyd', album: 'Wish You Were Here' },
    { id: 167, title: 'Wish You Were Here', artist: 'Pink Floyd', album: 'Wish You Were Here' },
    { id: 168, title: 'Shine On You Crazy Diamond (Parts VI–IX)', artist: 'Pink Floyd', album: 'Wish You Were Here' },
    { id: 169, title: 'In the Flesh?', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 170, title: 'The Thin Ice', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 171, title: 'Another Brick in the Wall, Part 1', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 172, title: 'The Happiest Days of Our Lives', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 173, title: 'Another Brick in the Wall, Part 2', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 174, title: 'Mother', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 175, title: 'Goodbye Blue Sky', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 176, title: 'Empty Spaces', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 177, title: 'Young Lust', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 178, title: 'One of My Turns', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 179, title: "Don't Leave Me Now", artist: 'Pink Floyd', album: 'The Wall' },
    { id: 180, title: 'Another Brick in the Wall, Part 3', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 181, title: 'Goodbye Cruel World', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 182, title: 'Pigs on the Wing (Part 1)', artist: 'Pink Floyd', album: 'Animals' },
    { id: 183, title: 'Dogs', artist: 'Pink Floyd', album: 'Animals' },
    { id: 184, title: 'Pigs (Three Different Ones)', artist: 'Pink Floyd', album: 'Animals' },
    { id: 185, title: 'Sheep', artist: 'Pink Floyd', album: 'Animals' },
    { id: 186, title: 'Pigs on the Wing (Part 2)', artist: 'Pink Floyd', album: 'Animals' },
    { id: 187, title: 'Hey You', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 188, title: 'Is There Anybody Out There?', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 189, title: 'Nobody Home', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 190, title: 'Vera', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 191, title: 'Bring the Boys Back Home', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 192, title: 'Comfortably Numb', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 193, title: 'The Show Must Go On', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 194, title: 'In the Flesh', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 195, title: 'Run Like Hell', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 196, title: 'Waiting for the Worms', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 197, title: 'Stop', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 198, title: 'The Trial', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 199, title: 'Outside the Wall', artist: 'Pink Floyd', album: 'The Wall' },
    { id: 200, title: 'One of These Days', artist: 'Pink Floyd', album: 'Meddle' },
    { id: 201, title: 'A Pillow of Winds', artist: 'Pink Floyd', album: 'Meddle' },
    { id: 202, title: 'Fearless', artist: 'Pink Floyd', album: 'Meddle' },
    { id: 203, title: 'San Tropez', artist: 'Pink Floyd', album: 'Meddle' },
    { id: 204, title: 'Seamus', artist: 'Pink Floyd', album: 'Meddle' },
    { id: 205, title: 'Echoes', artist: 'Pink Floyd', album: 'Meddle' },
];
